import fs from "node:fs/promises";
import path from "node:path";

import type { CSpellSettings } from "cspell";
import YAML from "yaml";

export const CONFIG_HEADER = `\
# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
# This file is @generated by <https://github.com/liblaf/cspell-init>.
# DO NOT EDIT!
`;

export async function saveConfig(file: string, settings: CSpellSettings): Promise<void> {
  const text: string = CONFIG_HEADER + YAML.stringify(settings, null, 2);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, text);
}
