import type { CSpellSettings } from "cspell";

export const CONFIG_HEADER = `\
# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
# This file is @generated by <https://github.com/liblaf/cspell-init>.
# DO NOT EDIT!
`;

export const DEFAULT_SETTINGS: CSpellSettings = {
  allowCompoundWords: true,
  cache: { useCache: true },
  caseSensitive: false,
  enableGlobDot: true,
  ignorePaths: [
    // CSpell
    ".cspell.*",
    "cspell.*",
    // lock files
    "*-lock.*",
    "*.lock",
    "go.sum",
    // images
    "*.png",
    // videos
    "*.avi",
    "*.mp4",
    // 3D models
    "*.glb",
    "*.landmarks.json",
    "*.msh",
    "*.obj",
    "*.ply",
    "*.series",
    "*.stl",
    "*.vti",
    "*.vtkhdf",
    "*.vtm",
    "*.vtp",
    "*.vtr",
    "*.vts",
    "*.vtu",
  ],
  ignoreRandomStrings: true,
  maxFileSize: "32KB",
  useGitignore: true,
};
