import type { CSpellSettings } from "cspell";

export const CONFIG_HEADER = `\
# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
# This file is @generated by <https://github.com/liblaf/cspell-init>.
# DO NOT EDIT!
`;

export const DEFAULT_SETTINGS: CSpellSettings = {
  allowCompoundWords: true,
  cache: { useCache: true },
  caseSensitive: false,
  enableGlobDot: true,
  ignorePaths: [
    ".cspell.*",
    "*-lock.*",
    "*.lock",
    "*.vtm",
    "*.vtp",
    "*.vtu",
    "cspell.*",
    "go.sum",
  ],
  ignoreRandomStrings: true,
  maxFileSize: "500KB",
  useGitignore: true,
};
